### ISSUE TITLE
serviceComb集成springcloudgateway无法使用微服务id进行路由导航

### ISSUE THREAD

**Issue by xcl2551** [huaweicloud/spring-cloud-huawei#111]
### 同样使用例子中的spring-cloud-starter-huawei-servicecomb-discovery进行服务注册
测试可以使用服务id进行路由导航
### gateway使用spring-cloud-starter-huawei-servicecomb-discovery,
服务提供者
 <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot-starter-provider</artifactId>
            <version>1.1.0</version>
 </dependency>
进行注册, 可以使用uri的方式进行路由,但是使用微服务id的方式进行路由报如下错误
java.lang.IllegalStateException: Invalid host: lb://workspace_service
	at org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter.filter(RouteToRequestUrlFilter.java:86) ~[spring-cloud-gateway-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:138) ~[spring-cloud-gateway-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44) ~[spring-cloud-gateway-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:118) ~[spring-cloud-gateway-core-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) [reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.2.10.RELEASE.jar:3.2.10.RELEASE]

**Comment by GuoYL123** [comment]
服务提供者是java chassis的应用吗？org.apache.servicecomb 导入这个包是什么？

**Comment by xcl2551** [comment]
服务的提供者是java-chassis应用, spring-boot-starter-provider 导入的是cse注册相关

**Comment by bibichuan** [comment]
服务名不支持下划线，你把下划线去掉试试。
