### ISSUE TITLE
使用feignClient远程调用出现问题

### ISSUE THREAD

**Issue by wuzean** [huaweicloud/spring-cloud-huawei#1146]
通过feignClient用服务名调用，会出现读取ribbonConfigue报错，具体报错请看附件
[auth.txt](https://github.com/huaweicloud/spring-cloud-huawei/files/13749732/auth.txt)

**Comment by chengyouling** [comment]
错误日志：
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)

	at com.alibaba.cloud.sentinel.feign.SentinelInvocationHandler.invoke(SentinelInvocationHandler.java:107)

	at com.sun.proxy.$Proxy140.getToken(Unknown Source)

	at com.ruoyi.auth.service.impl.ThirdLoginServiceImpl.token(ThirdLoginServiceImpl.java:67)

	at com.ruoyi.auth.controller.TokenController.login(TokenController.java:47)

	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)

	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)

	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)

	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)

	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)

	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ribbonClientConfig' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.client.config.IClientConfig]: Factory method 'ribbonClientConfig' threw exception; nested exception is java.lang.RuntimeException: Property yaml is invalid

	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)

	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)

	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)

	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)

	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)

	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)

	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)

	... 81 more

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.client.config.IClientConfig]: Factory method 'ribbonClientConfig' threw exception; nested exception is java.lang.RuntimeException: Property yaml is invalid

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)

	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)

	... 95 more

Caused by: java.lang.RuntimeException: Property yaml is invalid

	at com.netflix.client.config.DefaultClientConfigImpl.loadProperties(DefaultClientConfigImpl.java:589)

	at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration.ribbonClientConfig(RibbonClientConfiguration.java:102)

	at sun.reflect.GeneratedMethodAccessor175.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

	... 96 more

框架版本信息：
版本：1.9.3-Hoxton
配置中心类型：config-center
Servicecomb引擎：1.0.x

定位过程：
根据堆栈信息，异常抛出位置为DefaultClientConfigImpl#loadProperties方法，Configuration props = ConfigurationManager.getConfigInstance().subset(restClientName)监听服务名相关配置，配置中心中全局配置、服务级配置均有服务名字.yaml配置项。

解决方案：
将全局配置中服务名.yaml文件移到服务级配置，问题解决。
