### ISSUE TITLE
启动报错。java.lang.IllegalStateException: Service id not legal hostname 

### ISSUE THREAD

**Issue by chaoqunxie** [huaweicloud/spring-cloud-huawei#1160]
日志：
16:05:34.439 [main] INFO  c.u.j.c.EnableEncryptablePropertiesBeanFactoryPostProcessor 48 - Post-processing PropertySource instances

16:05:34.636 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy

16:05:34.638 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource bootstrap [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:34.638 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper

16:05:34.639 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper

16:05:34.639 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper

16:05:34.639 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper

16:05:34.639 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:34.640 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource applicationConfig: [file:bootstrap.yml] (document #2) [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:34.640 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource applicationConfig: [file:bootstrap.yml] (document #0) [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:34.806 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker 335 - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$f25b9ad1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

16:05:34.913 [main] INFO  c.u.j.f.DefaultLazyPropertyFilter 31 - Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter

16:05:34.929 [main] INFO  c.u.j.r.DefaultLazyPropertyResolver 35 - Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver

16:05:34.934 [main] INFO  c.u.j.d.DefaultLazyPropertyDetector 35 - Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector

16:05:35.251 [main] INFO  c.u.j.c.EnableEncryptablePropertiesBeanFactoryPostProcessor 48 - Post-processing PropertySource instances

16:05:35.372 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy

16:05:35.374 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource bootstrap [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:35.374 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper

16:05:35.375 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper

16:05:35.375 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper

16:05:35.375 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper

16:05:35.375 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:35.376 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource applicationConfig: [file:bootstrap.yml] (document #2) [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:35.376 [main] INFO  c.u.j.EncryptablePropertySourceConverter 44 - Converting PropertySource applicationConfig: [file:bootstrap.yml] (document #0) [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper

16:05:35.546 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker 335 - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$f25b9ad1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

16:05:35.677 [main] INFO  c.u.j.f.DefaultLazyPropertyFilter 31 - Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter

16:05:35.747 [main] INFO  c.u.j.r.DefaultLazyPropertyResolver 35 - Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver

16:05:35.752 [main] INFO  c.u.j.d.DefaultLazyPropertyDetector 35 - Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector

  .   ____          _            __ _ _

 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \

( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )

  '  |____| .__|_| |_|_| |_\__, | / / / /

 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::        (v2.2.7.RELEASE)

  .   ____          _            __ _ _

 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \

( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )

  '  |____| .__|_| |_|_| |_\__, | / / / /

 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::        (v2.2.7.RELEASE)

16:05:36.843 [main] INFO  o.s.c.b.c.PropertySourceBootstrapConfiguration 101 - Located property source: CompositePropertySource {name='servicecomb', propertySources=[ServiceCombConfigPropertySource {name='servicecomb'}]}

16:05:36.850 [main] INFO  o.s.boot.SpringApplication 655 - The following profiles are active: huaweicloud

16:05:37.849 [main] INFO  o.s.c.b.c.PropertySourceBootstrapConfiguration 101 - Located property source: CompositePropertySource {name='servicecomb', propertySources=[ServiceCombConfigPropertySource {name='servicecomb'}]}

16:05:37.856 [main] INFO  o.s.boot.SpringApplication 655 - The following profiles are active: huaweicloud

16:05:39.908 [main] ERROR o.s.boot.SpringApplication 826 - Application run failed

java.lang.IllegalStateException: Service id not legal hostname (${external.dict.serviceName})

	at org.springframework.util.Assert.state(Assert.java:73)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:103)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:278)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:233)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:219)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:144)

	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:384)

	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:383)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120)

	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)

	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)

	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280)

	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96)

	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)

	at com.nariit.rmcp.ai.AiApplication.main(AiApplication.java:33)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)

	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)

16:05:41.160 [main] ERROR o.s.boot.SpringApplication 826 - Application run failed

java.lang.IllegalStateException: Service id not legal hostname (${external.dict.serviceName})

	at org.springframework.util.Assert.state(Assert.java:73)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:103)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:278)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:233)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:219)

	at org.springframework.cloud.openfeign.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:144)

	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:384)

	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:383)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148)

	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBea

配置截图： bootstrap.yaml
<img width="1275" alt="image" src="https://github.com/huaweicloud/spring-cloud-huawei-samples/assets/44899524/02f9c203-cffa-4453-b81b-460353c067de">

配置中心
<img width="1245" alt="image" src="https://github.com/huaweicloud/spring-cloud-huawei-samples/assets/44899524/3c5341c1-8a6e-4134-bf82-092f9c51a9e7">

依赖：
<img width="664" alt="image" src="https://github.com/huaweicloud/spring-cloud-huawei-samples/assets/44899524/d412d4df-5bb0-46e2-aec6-c359a58c45e0">

feign:
<img width="799" alt="image" src="https://github.com/huaweicloud/spring-cloud-huawei-samples/assets/44899524/ca226e1a-2f6d-4898-b0cd-f7e5160b35ae">

**Comment by chengyouling** [comment]
java.lang.IllegalStateException: Service id not legal hostname (${external.dict.serviceName})

**Comment by chaoqunxie** [comment]
我修改了bootstrap.yaml ，升级了springboot 以及springcloud版本 添加了 bootstrap依赖，发现如下报错 是哪边配置错误或者缺失么？
<img width="1506" alt="image" src="https://github.com/huaweicloud/spring-cloud-huawei/assets/44899524/8d8126a3-1efc-460f-8906-592c78dae037">

**Comment by chengyouling** [comment]
kie配置中心的端口是30110

**Comment by chaoqunxie** [comment]
谢谢大佬 发现是环境变量替换了bootstrap里面的配置 我们需要多个注册中心切换，我bootstrap配置profiles为 eureka 并且排除了huawei依赖 启动会报如下错
<img width="1528" alt="image" src="https://github.com/huaweicloud/spring-cloud-huawei/assets/44899524/24e66386-130f-42d8-a370-2aa9ce96b92b">

**Comment by chengyouling** [comment]
从你截图来看只是剔除了bean的加载不是剔除了依赖，依赖是在pom中处理建议在pom中也声明profile去加载各自的依赖：
<profiles>
    <profile>
      <id>cse</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <dependencies>
        <dependency>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>eureka</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <dependencies>
        <dependency>
        </dependency>
      </dependencies>
    </profile>
<profiles>

**Comment by chaoqunxie** [comment]
感谢大佬，使用pom profile确实能解决问题 但是这个需要重新打包项目 我们之前是nacos和eureka可以直接通过配置文件切换即可 有什么方法能够让cse也这样呢 另外cse需要的springboot springcloud的版本可以在哪里查询到

**Comment by chengyouling** [comment]
你如果是购买了华为云的Nacos引擎，那么你也是可以通过改配置 实现兼容，直接注册到nacos

Servicecomb引擎对springboot springcloud的版本没什么要求

spring-cloud-huawei与springboot springcloud的版本对应关系可以看首页https://github.com/huaweicloud/spring-cloud-huawei

**Comment by chengyouling** [comment]
@chaoqunxie 是否还有其他问题？没问题我这边结束issue
