### ISSUE TITLE
kie查询配置异常

### ISSUE THREAD

**Issue by chaoqunxie** [huaweicloud/spring-cloud-huawei#1221]

**Comment by chengyouling** [comment]
堆栈信息给全点

**Comment by chaoqunxie** [comment]
> 堆栈信息给全点，上面kie查询的日志也贴出来

这是详细报错 查询kie 报错500 	... 5 common frames omitted

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:102)

}

 "detail": "context deadline exceeded"

 "errorMessage": "internal server error",

 "errorCode": "500001",

Caused by: org.apache.servicecomb.config.common.exception.OperationException: read response failed. status:500; message:Internal Server Error; content:{

	at java.lang.Thread.run(Thread.java:748)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at org.apache.servicecomb.http.client.task.AbstractTask.lambda$startTask$1(AbstractTask.java:84)

	at org.apache.servicecomb.config.kie.client.KieConfigManager$PollConfigurationTask.execute(KieConfigManager.java:124)

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:105)

org.apache.servicecomb.config.common.exception.OperationException: read response failed. 

17:41:53.247 [config-center-configuration-task] ERROR o.a.s.c.k.c.KieConfigManager$PollConfigurationTask 136 - get configurations from KieConfigCenter failed, and will try again.

}

 "detail": "context deadline exceeded"

 "errorMessage": "internal server error",

 "errorCode": "500001",

17:41:53.246 [config-center-configuration-task] ERROR o.a.s.config.kie.client.KieClient 104 - query configuration from https://25.213.59.161:30110/v1/default/kie/kv?label=app%3Armcp&label=service%3Armcp-ai&label=environment%3Aproduction&label=version%3A0.0.1&&revision=53&match=exact&wait=10s failed, message=read response failed. status:500; message:Internal Server Error; content:{

	... 5 common frames omitted

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:102)

}

 "detail": "context deadline exceeded"

 "errorMessage": "internal server error",

 "errorCode": "500001",

Caused by: org.apache.servicecomb.config.common.exception.OperationException: read response failed. status:500; message:Internal Server Error; content:{

	at java.lang.Thread.run(Thread.java:748)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at org.apache.servicecomb.http.client.task.AbstractTask.lambda$startTask$1(AbstractTask.java:84)

	at org.apache.servicecomb.config.kie.client.KieConfigManager$PollConfigurationTask.execute(KieConfigManager.java:124)

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:105)

org.apache.servicecomb.config.common.exception.OperationException: read response failed. 

17:41:52.816 [config-center-configuration-task] ERROR o.a.s.c.k.c.KieConfigManager$PollConfigurationTask 136 - get configurations from KieConfigCenter failed, and will try again.

}

 "detail": "context deadline exceeded"

 "errorMessage": "internal server error",

 "errorCode": "500001",

17:41:52.816 [config-center-configuration-task] ERROR o.a.s.config.kie.client.KieClient 104 - query configuration from https://25.213.59.161:30110/v1/default/kie/kv?label=app%3Armcp&label=service%3Armcp-ai&label=environment%3Aproduction&&revision=53&match=exact&wait=10s failed, message=read response failed. status:500; message:Internal Server Error; content:{

	... 5 common frames omitted

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:102)

}

 "detail": "context deadline exceeded"

 "errorMessage": "internal server error",

 "errorCode": "500001",

Caused by: org.apache.servicecomb.config.common.exception.OperationException: read response failed. status:500; message:Internal Server Error; content:{

	at java.lang.Thread.run(Thread.java:748)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at org.apache.servicecomb.http.client.task.AbstractTask.lambda$startTask$1(AbstractTask.java:84)

	at org.apache.servicecomb.config.kie.client.KieConfigManager$PollConfigurationTask.execute(KieConfigManager.java:124)

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:105)

org.apache.servicecomb.config.common.exception.OperationException: read response failed. 

17:41:47.382 [config-center-configuration-task] ERROR o.a.s.c.k.c.KieConfigManager$PollConfigurationTask 136 - get configurations from KieConfigCenter failed, and will try again.

}

 "detail": "context deadline exceeded"

 "errorMessage": "internal server error",

 "errorCode": "500001",

17:41:47.382 [config-center-configuration-task] ERROR o.a.s.config.kie.client.KieClient 104 - query configuration from https://25.213.59.161:30110/v1/default/kie/kv?label=app%3Armcp&label=environment%3Aproduction&&revision=53&match=exact&wait=10s failed, message=read response failed. status:500; message:Internal Server Error; content:{

	... 5 common frames omitted

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:102)

}

 "detail": "context deadline exceeded"

 "errorMessage": "internal server error",

 "errorCode": "500001",

Caused by: org.apache.servicecomb.config.common.exception.OperationException: read response failed. status:500; message:Internal Server Error; content:{

	at java.lang.Thread.run(Thread.java:748)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at org.apache.servicecomb.http.client.task.AbstractTask.lambda$startTask$1(AbstractTask.java:84)

	at org.apache.servicecomb.config.kie.client.KieConfigManager$PollConfigurationTask.execute(KieConfigManager.java:124)

	at org.apache.servicecomb.config.kie.client.KieClient.queryConfigurations(KieClient.java:105)

org.apache.servicecomb.config.common.exception.OperationException: read response failed. 

17:41:43.240 [config-center-configuration-task] ERROR o.a.s.c.k.c.KieConfigManager$PollConfigurationTask 136 - get configurations from KieConfigCenter failed, and will try again.

}

**Comment by chengyouling** [comment]
你这个是一直包这个错，还是特殊情况下的错误，能简单描述下场景吗？

**Comment by chaoqunxie** [comment]
> 你这个是一直报这个错，还是特殊情况下的错误，能简单描述下场景吗？

一直报这个错

**Comment by chengyouling** [comment]
那估计是servicecomb引擎那边有问题，你找下一线或者产品平台提一个问题，或者你创建一个会议发我邮箱，我们一起看看

**Comment by chaoqunxie** [comment]
> 那估计是servicecomb引擎那边有问题，你找下一线或者产品平台提一个问题，或者你创建一个会议发我邮箱，我们一起看看
好的，感谢，请问下您的邮箱是什么，这会有时间么，我这边创建一个腾讯会议

**Comment by chaoqunxie** [comment]
大佬有空加这个会议 谢超群 邀请您参加腾讯会议会议主题：谢超群的快速会议会议时间：2024/02/04 10:09-11:09 (GMT+08:00) 中国标准时间 - 北京点击链接直接加入会议：https://meeting.tencent.com/dm/VEGk4eg1mCvu#腾讯会议：677-922-978复制该信息，打开手机腾讯会议即可参与发自我的 iPhone在 2024年2月4日，09:31，Cheng YouLing ***@***.***> 写道：﻿
那估计是servicecomb引擎那边有问题，你找下一线或者产品平台提一个问题，或者你创建一个会议发我邮箱，我们一起看看

**Comment by chaoqunxie** [comment]
大佬现在feign调用报这个错

**Comment by chaoqunxie** [comment]
> 大佬现在feign调用报这个错

这个报错是因为其他的jar包对ribbon有依赖 排出后可以了，但是现在报错 503 during post to http://rmcp-service-dict/get-map-by-sn   load balancer does contain an instance for service rmcp-service-dict

**Comment by chaoqunxie** [comment]
> > 大佬现在feign调用报这个错
> 
> 这个报错是因为其他的jar包对ribbon有依赖 排出后可以了，但是现在报错 503 during post to http://rmcp-service-dict/get-map-by-sn load balancer does contain an instance for service rmcp-service-dict

实力列表里面有这两个服务

**Comment by chengyouling** [comment]
应用名、环境是否相同，可以在客户端看看有没有instance changed信息，有的话对下实例IP是否对的上

在 2024-02-08 11:33:19，chaoqunxie ***@***.***> 写道：


大佬现在feign调用报这个错

这个报错是因为其他的jar包对ribbon有依赖 排出后可以了，但是现在报错 503 during post to http://rmcp-service-dict/get-map-by-sn load balancer does contain an instance for service rmcp-service-dict

实力列表里面有这两个服务

**Comment by chaoqunxie** [comment]
应用名，环境是相同的，发现不管是直连ip 还是走注册中心都会报这个错

**Comment by chaoqunxie** [comment]
> 应用名、环境是否相同，可以在客户端看看有没有instance changed信息，有的话对下实例IP是否对的上 在 2024-02-08 11:33:19，chaoqunxie ***@***.***> 写道： 大佬现在feign调用报这个错 这个报错是因为其他的jar包对ribbon有依赖 排出后可以了，但是现在报错 503 during post to http://rmcp-service-dict/get-map-by-sn load balancer does contain an instance for service rmcp-service-dict 实力列表里面有这两个服务 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

客户端看看有没有instance changed信息，这个在哪里查看

**Comment by chengyouling** [comment]
那你核对下部署的虚拟机跟servicecomb引擎是否在同一个VPC下面

**Comment by chengyouling** [comment]
> > 应用名、环境是否相同，可以在客户端看看有没有instance changed信息，有的话对下实例IP是否对的上 在 2024-02-08 11:33:19，chaoqunxie _**@**_._**> 写道： 大佬现在feign调用报这个错 这个报错是因为其他的jar包对ribbon有依赖 排出后可以了，但是现在报错 503 during post to http://rmcp-service-dict/get-map-by-sn load balancer does contain an instance for service rmcp-service-dict 实力列表里面有这两个服务 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> 客户端看看有没有instance changed信息，这个在哪里查看

在客户端的业务日志里面可以看到

**Comment by chaoqunxie** [comment]
方便远程帮忙看下么，我给您发个会议链接发自我的 iPhone在 2024年2月18日，09:15，Cheng YouLing ***@***.***> 写道：﻿
那你核对下部署的虚拟机跟servicecomb引擎是否在同一个VPC下面

**Comment by chaoqunxie** [comment]
> 那你核对下部署的虚拟机跟servicecomb引擎的VPC是否相同

两个服务用的同一个kie 配置中心都读到了，网页上也能看到两个服务是启动的

**Comment by chengyouling** [comment]
> 方便远程帮忙看下么，我给您发个会议链接发自我的 iPhone在 2024年2月18日，09:15，Cheng YouLing ***@***.***> 写道：﻿ 那你核对下部署的虚拟机跟servicecomb引擎是否在同一个VPC下面 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

可以的

**Comment by chaoqunxie** [comment]
> > 方便远程帮忙看下么，我给您发个会议链接发自我的 iPhone在 2024年2月18日，09:15，Cheng YouLing _**@**_._**> 写道：﻿ 那你核对下部署的虚拟机跟servicecomb引擎是否在同一个VPC下面 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.**_>
> 
> 可以的，麻烦发下链接呢

好的 今天下午您那边有空么？我给您发邮件，这是我们两个服务的日志

这是rmcp-service-dict的启动日志
2024-02-18 10:30:02.836  INFO 14 --- [           main] o.a.s.foundation.common.net.NetUtils     : add ipv4 network interface:eth0,host address:10.1.0.211
2024-02-18 10:30:02.836  INFO 14 --- [           main] o.a.s.foundation.common.net.NetUtils     : localhost hostName=rmcp-service-dict-66cd5cc657-ztpt5, hostAddress=10.1.0.211.
2024-02-18 10:30:02.837  INFO 14 --- [           main] o.a.s.foundation.common.net.NetUtils     : Host address info ipV4=10.1.0.211, ipV6=10.1.0.211.
2024-02-18 10:30:03.708  INFO 14 --- [           main] c.h.common.disovery.ServiceCenterUtils   : initialize discovery server=[https://25.213.59.161:30100, https://25.213.59.134:30100]
2024-02-18 10:30:03.730  INFO 14 --- [           main] c.h.common.disovery.ServiceCenterUtils   : initialize discovery server=[https://25.213.59.161:30100, https://25.213.59.134:30100]
2024-02-18 10:30:04.412  WARN 14 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.


这是rmcp-ai服务的启动日志
2024-02-18 11:15:07.330  INFO 14 --- [           main] o.a.s.foundation.common.net.NetUtils     : localhost hostName=rmcp-ai-569bf46466-6rdsn, hostAddress=10.1.1.16.
2024-02-18 11:15:07.331  INFO 14 --- [           main] o.a.s.foundation.common.net.NetUtils     : Host address info ipV4=10.1.1.16, ipV6=10.1.1.16.
2024-02-18 11:15:24.117  INFO 14 --- [           main] c.h.common.disovery.ServiceCenterUtils   : initialize discovery server=[https://25.213.59.161:30100, https://25.213.59.134:30100]
2024-02-18 11:15:24.185  INFO 14 --- [           main] c.h.common.disovery.ServiceCenterUtils   : initialize discovery server=[https://25.213.59.161:30100, https://25.213.59.134:30100]
2024-02-18 11:15:26.518  INFO 14 --- [           main] DiscoveryClientOptionalArgsConfiguration : Eureka HTTP Client uses RestTemplate.
2024-02-18 11:15:26.610  WARN 14 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
2024-02-18 11:15:26.611  WARN 14 --- [           main] o.s.c.n.core.CoreAutoConfiguration       : This module is deprecated. It will be removed in the next major release. Please use spring-cloud-netflix-hystrix instead.

rmcp-ai调用rmcp-service-dict报错feign.FeignException$ServiceUnavailable: [503] during [POST] to [http://rmcp-service-dict/dict-list] [DictFeignClient#list(ReqDictVO)]: [Load balancer does not contain an instance for the service rmcp-service-dict]

**Comment by chengyouling** [comment]
可以的，下午直接发我链接，服务的日志比较少，需要比较全的日志去定位

**Comment by chaoqunxie** [comment]
大佬麻烦进一下会议 流沙 邀请您参加腾讯会议会议主题：流沙的快速会议会议时间：2024/02/19 14:14-15:14 (GMT+08:00) 中国标准时间 - 北京点击链接直接加入会议：https://meeting.tencent.com/dm/CavuPZDpXwtv#腾讯会议：498-132-641复制该信息，打开手机腾讯会议即可参与发自我的 iPhone在 2024年2月19日，10:26，Cheng YouLing ***@***.***> 写道：﻿
可以的，下午直接发我链接，服务的日志比较少，需要比较全的日志去定位
