### ISSUE TITLE
master代码启动注册报错

### ISSUE THREAD

**Issue by Hoysun** [huaweicloud/spring-cloud-huawei#347]
![image](https://user-images.githubusercontent.com/33214952/106075782-4569ca80-6149-11eb-8575-f62c29995c6c.png)

2021-01-28 09:03:32.838  INFO 19996 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService
2021-01-28 09:03:33.305  INFO 19996 --- [           main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2021-01-28 09:03:34.776  INFO 19996 --- [           main] o.s.cloud.commons.util.InetUtils         : Cannot determine local hostname
2021-01-28 09:03:35.154  INFO 19996 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8002 (http) with context path ''
2021-01-28 09:03:35.178 ERROR 19996 --- [icloud.registry] c.h.s.d.r.ServiceCombServiceRegistry     : Unexpected exception in register. 

java.lang.NullPointerException: null
	at com.huaweicloud.swagger.ServiceCombDocumentationSwaggerMapper.documentationToSwaggers(ServiceCombDocumentationSwaggerMapper.java:84) ~[spring-cloud-huawei-swagger-1.3.3-Hoxton-SNAPSHOT.jar:1.3.3-Hoxton-SNAPSHOT]
	at com.huaweicloud.swagger.ServiceCombSwaggerHandlerImpl.init(ServiceCombSwaggerHandlerImpl.java:75) ~[spring-cloud-huawei-swagger-1.3.3-Hoxton-SNAPSHOT.jar:1.3.3-Hoxton-SNAPSHOT]
	at com.huaweicloud.servicecomb.discovery.registry.ServiceCombServiceRegistry.getMicroservice(ServiceCombServiceRegistry.java:133) ~[spring-cloud-huawei-servicecomb-discovery-1.3.3-Hoxton-SNAPSHOT.jar:1.3.3-Hoxton-SNAPSHOT]
	at com.huaweicloud.servicecomb.discovery.registry.ServiceCombServiceRegistry.lambda$asyncRegister$1(ServiceCombServiceRegistry.java:97) ~[spring-cloud-huawei-servicecomb-discovery-1.3.3-Hoxton-SNAPSHOT.jar:1.3.3-Hoxton-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]

2021-01-28 09:03:36.833  INFO 19996 --- [           main] o.s.cloud.commons.util.InetUtils         : Cannot determine local hostname
2021-01-28 09:03:36.833  INFO 19996 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2021-01-28 09:03:36.879  INFO 19996 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2021-01-28 09:03:36.986  INFO 19996 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2021-01-28 09:03:37.447  INFO 19996 --- [           main] c.h.sample.ProviderApplication           : Started ProviderApplication in 25.864 seconds (JVM running for 31.977)

**Comment by liubao68** [comment]
这个错误和使用的spring boot版本有关系。 Hoxton支持的是2.2.x版本spring boot，不支持更高版本的spring boot。

**Comment by liubao68** [comment]
升级spring cloud huawei的spring cloud基线版本到Hoxton-SR8, spring boot基线版本到2.3.5-RELEASE

**Comment by liubao68** [comment]
will be available in 1.6.0
