### ISSUE TITLE
1.5.1-greenwich版本心跳异常问题，报错信息org.apache.http.NoHttpResponseException: XXX.XXX.XXX.XXX:XXXX failed to respond

### ISSUE THREAD

**Issue by Marvin-Mao** [huaweicloud/spring-cloud-huawei#463]
2021-07-30 08:31:56.727 [pool-3-thread-1] WARN   --- c.h.s.d.r.HeartbeatScheduler.lambda$add$0(HeartbeatScheduler.java:83) --- heartbeat failed. com.huaweicloud.common.exception.RemoteServerUnavailableException: server is unavailable. message=XXX.XXX.XXX.XXX:XXXX failed to respond

	at com.huaweicloud.common.transport.DefaultHttpTransport.execute(DefaultHttpTransport.java:197) ~[spring-cloud-huawei-common-1.5.1-Greenwich.jar!/:1.5.1-Greenwich]
	at com.huaweicloud.common.transport.DefaultHttpTransport.sendPutRequest(DefaultHttpTransport.java:226) ~[spring-cloud-huawei-common-1.5.1-Greenwich.jar!/:1.5.1-Greenwich]
	at com.huaweicloud.servicecomb.discovery.client.ServiceCombClient.heartbeat(ServiceCombClient.java:401) ~[spring-cloud-huawei-servicecomb-discovery-1.5.1-Greenwich.jar!/:1.5.1-Greenwich]
	at com.huaweicloud.servicecomb.discovery.registry.HeartbeatScheduler.lambda$add$0(HeartbeatScheduler.java:69) ~[spring-cloud-huawei-servicecomb-discovery-1.5.1-Greenwich.jar!/:1.5.1-Greenwich]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.1.19.RELEASE.jar!/:5.1.19.RELEASE]

Caused by: org.apache.http.NoHttpResponseException: XXX.XXX.XXX.XXX:XXXX failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.13.jar!/:4.4.13]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.13.jar!/:4.4.13]

该问题和https://github.com/huaweicloud/spring-cloud-huawei/issues/273问题非常像，但是当前已经是1.3.8以上版本，理论上已经解决了已知问题，请进一步分析。

**Comment by liubao68** [comment]
这个错误是什么情况下抛出 ？ 出现频率怎么样？需要提供一些可供分析的线索或者重现条件才好分析。 

如果出现频率非常低，有可能是网络问题。 如果有规律出现， 可以试试 1.6.0-Greenwich 或者 1.6.1-Hoxton。

**Comment by liubao68** [comment]
相同的问题使用1.6.0-Greenwich测试，功能正常。
