### ISSUE TITLE
1.6.1-Finchley using management call “not implemented” exception

### ISSUE THREAD

**Issue by chengyouling** [huaweicloud/spring-cloud-huawei#733]
背景：application.yaml中配置了management.server的相关信息后出现“not implemented”异常。
引起原因：配置management.server相关信息后，服务注册时候会调用registerManagement()方法，1.6.1-Finchley框架未实现该方法，所以出现异常信息。
错误日志：
2022-06-14 17:54:52.754 - [] - [main] ERROR org.springframework.boot.SpringApplication.reportFailure(837) - Application run failed
java.lang.IllegalStateException: not implemented
	at com.huaweicloud.servicecomb.discovery.registry.ServiceCombAutoServiceRegistration.getManagementRegistration(ServiceCombAutoServiceRegistration.java:64)
	at com.huaweicloud.servicecomb.discovery.registry.ServiceCombAutoServiceRegistration.getManagementRegistration(ServiceCombAutoServiceRegistration.java:28)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.registerManagement(AbstractAutoServiceRegistration.java:218)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:112)
	at com.huaweicloud.servicecomb.discovery.registry.ServiceCombAutoServiceRegistration.start(ServiceCombAutoServiceRegistration.java:39)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:262)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:358)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:166)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
	at cn.hsa.cep.rtc.HsaHuaweiApplication.main(HsaHuaweiApplication.java:24)

**Comment by Shoothzj** [comment]
Hi, @chengyouling I don't think `Finchley` is normally supported neither by springcloud or springcloudhuawei. Can you update to a high version like 2020.0.x?

**Comment by chengyouling** [comment]
some high version is complete repair,I will check again and update.
