### ISSUE TITLE
CanaryServiceInstanceFilter抛空指针异常

### ISSUE THREAD

**Issue by markey92** [huaweicloud/spring-cloud-huawei#754]
spring-cloud-huawei的1.10.0-2021.0.x版本，定时任务通过BlockingLoadBalancerClient获取微服务实例信息，CanaryServiceInstanceFilter抛空指针异常。。

2022-06-22 09:10:00,049Z(15051546)|ERROR|MyClusteredScheduler_Worker-2raceId|MyClusteredScheduler_Worker-2|org.quartz.core.JobRunShell.run(JobRunShell.java:211)|Job DEFAULT.InstanceNewSpecSyncJob threw an unhandled Exception:
java.lang.NullPointerException: null
        at com.huaweicloud.router.client.loabalancer.CanaryServiceInstanceFilter.filter(CanaryServiceInstanceFilter.java:66) ~[spring-cloud-huawei-router-client-1.10.0-2021.0.x.jar:1.10.0-2021.0.x]
        at com.huaweicloud.router.client.loabalancer.RouterServiceInstanceListSupplier.filter(RouterServiceInstanceListSupplier.java:82) ~[spring-cloud-huawei-router-client-1.10.0-2021.0.x.jar:1.10.0-2021.0.x]
        at com.huaweicloud.router.client.loabalancer.RouterServiceInstanceListSupplier.lambda$get$0(RouterServiceInstanceListSupplier.java:66) ~[spring-cloud-huawei-router-client-1.10.0-2021.0.x.jar:1.10.0-2021.0.x]
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:98) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:44) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:421) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:686) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:250) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[reactor-core-3.4.17.jar:3.4.17]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292) ~[reactor-core-3.4.17.jar:3.4.17]

**Comment by markey92** [comment]
> 看起来是bug，能帮忙给下重现条件吗？

import org.springframework.cloud.client.loadbalancer.LoadBalancerClient;

    @Autowired
    private LoadBalancerClient loadBalancer;
	
	    public ServiceInstance getOneInstance(String serviceName) {
        ServiceInstance instance = loadBalancer.choose(serviceName);
        if (instance == null) {
            LOGGER.info("cannot get {} instance from loadbalancer", serviceName);
            return null;
        }
        return instance;
    }

定时任务调用getOneInstance获取实例信息时报错
